"""add_user_foreign_key_to_user_achievements

Revision ID: 0d22e1b5e404
Revises: 4ed5fe9332db
Create Date: 2025-06-01 11:02:27.115763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d22e1b5e404'
down_revision: Union[str, None] = '4ed5fe9332db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
