"""update_achievements_with_flutter_compatibility

Revision ID: 4ed5fe9332db
Revises: 6f9e398676f1
Create Date: 2025-06-01 10:29:21.618233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed5fe9332db'
down_revision: Union[str, None] = '6f9e398676f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('achievements', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('user_achievements', sa.Column('is_notified', sa.Boolean(), nullable=False, server_default='false'))
    op.create_index(op.f('ix_user_achievements_achievement_id'), 'user_achievements', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    # Drop old column before creating new foreign keys
    op.drop_column('user_achievements', 'notified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_achievements', sa.Column('notified', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default='false'))
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_achievement_id'), table_name='user_achievements')
    op.drop_column('user_achievements', 'is_notified')
    op.alter_column('achievements', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
