"""refactor_to_base_model

Revision ID: 6f9e398676f1
Revises: 575e07da9357
Create Date: 2025-06-01 01:28:22.152798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9e398676f1'
down_revision: Union[str, None] = '575e07da9357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('achievements', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('history', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('scheduled_tasks', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('schedules', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('task_completions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('user_achievements', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('user_task_streaks', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'description')
    op.drop_column('user_task_streaks', 'description')
    op.drop_column('user_achievements', 'description')
    op.drop_column('tasks', 'description')
    op.drop_column('task_completions', 'description')
    op.drop_column('schedules', 'description')
    op.drop_column('scheduled_tasks', 'description')
    op.drop_column('history', 'description')
    op.alter_column('achievements', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
